In [1]:
# Завдання 1
# Створіть одновимірний масив (вектор) зі зворотнім порядком перших 10 натуральних чисел та виведіть його значення. 
reverse_list = list(range(10, 0, -1))

print(reverse_list)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [1]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число менше попереднього на 3, та виведіть його значення
rows = 3
cols = 3

matrix = [[0] * cols for _ in range(rows)]

current_value = 9

for i in range(rows):
    for j in range(cols):
        matrix[i][j] = current_value
        current_value -= 3

print("Двовимірний масив (матриця):")
for row in matrix:
    print(row)

Двовимірний масив (матриця):
[9, 6, 3]
[0, -3, -6]
[-9, -12, -15]


In [4]:
# Завдання 3
# Створіть масив розміром 8x8, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення. 
import numpy as np

# Розмір матриці
rows = 8
cols = 8

# Створення матриці розміром 8x8 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(1, 10, size=(rows, cols))

# Виведення значень матриці
print("Двовимірний масив (матриця):")
for row in matrix:
    print(row)

Двовимірний масив (матриця):
[8.91776779 1.65151787 1.76295691 3.0304528  7.82403644 1.78990994
 3.92182082 7.46620042]
[6.25891191 5.00267626 9.11509109 8.4778519  3.11755846 3.22115215
 6.78026649 6.87451163]
[2.23897721 6.83938012 9.27055409 7.10042314 2.25384365 3.57922853
 5.6469182  6.54357522]
[8.38198218 4.01413297 5.32800837 8.44780086 7.83070818 6.01510376
 8.58008854 6.95411429]
[3.95052841 9.51951377 1.32809962 6.87742114 8.4938608  5.2731427
 8.24479325 1.10894971]
[6.15015389 1.84794938 5.52296969 5.43454318 4.44498242 9.12409075
 8.73860107 9.35500706]
[9.12038878 9.98717132 2.14074668 7.96260815 9.7682473  6.05331759
 3.63606991 1.94407718]
[1.59009449 1.85750456 3.00113909 1.03767774 6.61274978 4.12756606
 4.48326627 1.45306557]


In [5]:
# Завдання 4
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток всіх елементів. 
import numpy as np

rows = 3
cols = 3

matrix = np.random.rand(rows, cols)

print("Двовимірний масив (матриця):")
print(matrix)

product = np.prod(matrix)

print("Добуток всіх елементів матриці:", product)

Двовимірний масив (матриця):
[[0.93213447 0.17938751 0.65010046]
 [0.77687944 0.25679203 0.67466133]
 [0.95069605 0.42456206 0.36510396]]
Добуток всіх елементів матриці: 0.0021561136795276987


In [7]:
# Завдання 5
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від -20 до 20 та виконайте на них поелементні операції додавання, віднімання та множення. 
import numpy as np

size = 6

array1 = np.random.randint(-20, 21, size)
array2 = np.random.randint(-20, 21, size)

print("Перший масив:", array1)
print("Другий масив:", array2)

add_result = np.add(array1, array2)
print("Результат додавання:", add_result)

subtraction_result = np.subtract(array1, array2)
print("Результат віднімання:", subtraction_result)

multiplication_result = np.multiply(array1, array2)
print("Результат множення:", multiplication_result)

Перший масив: [-10  -5 -10  -7  11   0]
Другий масив: [-11  -6  16 -15 -11 -11]
Результат додавання: [-21 -11   6 -22   0 -11]
Результат віднімання: [  1   1 -26   8  22  11]
Результат множення: [ 110   30 -160  105 -121    0]


In [10]:
# Завдання 6
# Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток. 
import numpy as np

size = 8

vector1 = np.random.randint(-10, 11, size)
vector2 = np.random.randint(-10, 11, size)

print("Перший вектор:", vector1)
print("Другий вектор:", vector2)

dot_product = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product)

Перший вектор: [-8  2  6 -3  9 -2 -7 -9]
Другий вектор: [ 1 -2  0 -7 10  0  2 -3]
Скалярний добуток: 112


In [13]:
# Завдання 7
# Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою. 
import numpy as np

rows1 = 3
cols1 = 2 
rows2 = 2
cols2 = 2

matrix1 = np.random.randint(1, 9, size=(rows1, cols1))
matrix2 = np.random.randint(1, 9, size=(rows2, cols2))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

result_matrix = np.dot(matrix1, matrix2)

print("\nРезультат перемноження матриць:")
print(result_matrix)

Перша матриця:
[[6 7]
 [1 8]
 [1 8]]

Друга матриця:
[[7 3]
 [5 6]]

Результат перемноження матриць:
[[77 60]
 [47 51]
 [47 51]]


In [17]:
# Завдання 8
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю
import numpy as np

rows, cols = 2, 2

matrix = np.random.randint(1, 11, size=(rows, cols))

print("Початкова матриця:")
print(matrix)

inverse_matrix = np.linalg.inv(matrix)
print("\nОбернена матриця:")
print(inverse_matrix)


Початкова матриця:
[[ 8 10]
 [ 6  5]]

Обернена матриця:
[[-0.25  0.5 ]
 [ 0.3  -0.4 ]]


In [18]:
# Завдання 9
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її. 
import numpy as np

rows, cols = 3, 3

matrix = np.random.randint(0, 2, size=(rows, cols))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[1 0 1]
 [1 1 1]
 [0 0 1]]

Транспонована матриця:
[[1 1 0]
 [0 1 0]
 [1 1 1]]


In [20]:
# Завдання 10 
# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор. 
import numpy as np

rows, cols = 3, 4
vector_size = 4

matrix = np.random.rand(rows, cols)

vector = np.random.randint(1, 11, size=vector_size)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

product_result = np.dot(matrix, vector)

print("\nРезультат добутку матриці на вектор:")
print(product_result)

Матриця:
[[0.2206893  0.22405331 0.44862405 0.35004231]
 [0.57490328 0.11506252 0.71241427 0.03565418]
 [0.57962257 0.81952468 0.25773238 0.06471996]]

Вектор:
[3 6 8 4]

Результат добутку матриці на вектор:
[6.99554934 8.25701589 8.9767547 ]


In [22]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного рядка матриці на відповідний елемент вектору. 
import numpy as np

rows, cols = 2, 3
vector_size = 3

matrix = np.random.randint(1, 11, size=(rows, cols))

vector = np.random.randint(1, 11, size=vector_size)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

result_sum = np.sum(matrix * vector, axis=1)

print("\nРезультат суми добутків елементів кожного рядка матриці на відповідний елемент вектору:")
print(result_sum)

Матриця:
[[ 3 10  2]
 [ 1  3  8]]

Вектор:
[3 7 9]

Результат суми добутків елементів кожного рядка матриці на відповідний елемент вектору:
[97 96]


In [25]:
# Завдання 12
# Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів першої матриці. 
import numpy as np

rows, cols = 6, 6

matrix1 = np.random.randint(1, 11, size=(rows, cols))
matrix2 = np.random.randint(1, 11, size=(rows, cols))

print("Перша матриця:")
print(matrix1)

print("Друга матриця:")
print(matrix2)

sum_of_elements = np.sum(matrix1)

print("\nСума елементів першої матриці:", sum_of_elements)

Перша матриця:
[[ 4  9  9 10  9  7]
 [ 6  9  9  9  2  7]
 [ 1  7  5  9  7  5]
 [ 5  4  2  5  7  1]
 [ 9  3  4  3  4  9]
 [ 9  5  7  7  6  8]]
Друга матриця:
[[ 7  7  4  7  9  5]
 [ 3  3  4  8  4  7]
 [ 2  2  7  7 10  6]
 [ 7  1  5  8  6  1]
 [ 7  3  8  9  9 10]
 [ 2 10  3  4  1  7]]

Сума елементів першої матриці: 222


In [26]:
# Завдання 13
# Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів. 
import numpy as np

rows, cols = 6, 6

matrix1 = np.random.rand(rows, cols)
matrix2 = np.random.rand(rows, cols)

print("Перша матриця:")
print(matrix1)

print("\nДруга матриця:")
print(matrix2)

difference_matrix = matrix1 - matrix2

print("\nРізниця елементів матриць:")
print(difference_matrix)

Перша матриця:
[[0.46650049 0.77362862 0.00579899 0.94780203 0.92228508 0.39869749]
 [0.55732784 0.8103913  0.41433935 0.46357562 0.36390157 0.78816234]
 [0.79354279 0.54617838 0.31451265 0.00861751 0.85456255 0.51677446]
 [0.83770154 0.5555996  0.14393883 0.36931965 0.23950666 0.74709705]
 [0.96388036 0.10664595 0.57694163 0.5478598  0.76082726 0.49208322]
 [0.64102234 0.26544102 0.99386569 0.25277905 0.58502415 0.48339022]]

Друга матриця:
[[0.04302697 0.78694013 0.94396685 0.8986837  0.72236488 0.85802326]
 [0.30044609 0.39973173 0.43031649 0.76721835 0.36732362 0.93324056]
 [0.22964642 0.0891977  0.5307825  0.28390874 0.86880807 0.62652104]
 [0.72452098 0.82896247 0.70665774 0.66615827 0.02149187 0.03665612]
 [0.66758613 0.12016221 0.59893991 0.70801439 0.95513788 0.14660702]
 [0.16880698 0.2971255  0.58401089 0.61417611 0.98398425 0.09235301]]

Різниця елементів матриць:
[[ 0.42347352 -0.01331151 -0.93816786  0.04911833  0.1999202  -0.45932576]
 [ 0.25688175  0.41065956 -0.0159771

In [27]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть добуток елементів матриці. 
import numpy as np

rows, cols = 3, 3

matrix = np.random.uniform(-10, 10, size=(rows, cols))

print("Матриця:")
print(matrix)

product_result = np.prod(matrix)

print("\nДобуток елементів матриці:", product_result)

Матриця:
[[-5.53929208 -7.38468091 -6.42367387]
 [ 5.54284401 -9.10917401 -7.53539396]
 [-6.2713855  -6.69402094  5.66603668]]

Добуток елементів матриці: -23780284.513521455


In [28]:
# Завдання 15
# Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному рядку матриці. 
import numpy as np

rows, cols = 7, 7

matrix = np.random.rand(rows, cols)

print("Матриця:")
print(matrix)

max_elements_vector = np.max(matrix, axis=1, keepdims=True)

print("\nВектор-стовпчик з найбільшими елементами у кожному рядку:")
print(max_elements_vector)

Матриця:
[[0.37253058 0.70418401 0.11270606 0.37225477 0.67456354 0.39762643
  0.56757741]
 [0.61454538 0.02329404 0.30245491 0.78116916 0.94693549 0.06720522
  0.17467536]
 [0.11121951 0.17738267 0.32731687 0.78049208 0.20123009 0.47366771
  0.36077653]
 [0.91861802 0.85320362 0.09959365 0.40839451 0.43228525 0.06701809
  0.37199996]
 [0.73600166 0.17049331 0.03948749 0.25428305 0.05013929 0.25015528
  0.21525516]
 [0.82934432 0.21383271 0.17395669 0.67949579 0.79593847 0.64607329
  0.38859739]
 [0.23450098 0.40078294 0.70720117 0.90256284 0.57207229 0.42048385
  0.18267642]]

Вектор-стовпчик з найбільшими елементами у кожному рядку:
[[0.70418401]
 [0.94693549]
 [0.78049208]
 [0.91861802]
 [0.73600166]
 [0.82934432]
 [0.90256284]]


In [ ]:
# Виконав усі завдання по темі елементи лінійної алгебри